# Generated by Django 4.2.13 on 2024-07-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0002_safetyfilter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrecord',
            name='travel_date2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
