# Generated by Django 4.2.11 on 2024-07-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0004_accommodation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='description',
            new_name='review_score',
        ),
    ]
