# Generated by Django 4.2.11 on 2024-07-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0006_alter_accommodation_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='review_score',
            field=models.CharField(max_length=200),
        ),
    ]
