# Generated by Django 4.2.11 on 2024-07-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0008_alter_accommodation_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='price',
            field=models.PositiveIntegerField(max_length=200),
        ),
    ]
