# Generated by Django 4.2.11 on 2024-07-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0009_alter_accommodation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrecord',
            name='people',
            field=models.PositiveIntegerField(max_length=200),
        ),
    ]
