# Generated by Django 4.2.11 on 2024-07-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0010_alter_searchrecord_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='searchrecord',
            name='people',
            field=models.PositiveIntegerField(),
        ),
    ]
