# Generated by Django 4.2.11 on 2024-07-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0011_alter_accommodation_price_alter_searchrecord_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_type', models.CharField(choices=[('price_asc', '가격 낮은 순서'), ('price_desc', '가격 높은 순서'), ('rating_asc', '별점 낮은 순서'), ('rating_desc', '별점 높은 순서')], max_length=20, unique=True)),
            ],
        ),
    ]
