# Generated by Django 5.0.6 on 2024-07-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0014_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
