# Generated by Django 5.0.6 on 2024-07-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homst', '0018_alter_post_created_at_alter_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
